spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
#thymeleaf end
  mvc:
    view:
      prefix: /resources/static/
      suffix: .html
  resources:
    static-locations: classpath:/templates/
server:
  port: 82