server:
  port: 8763

mybatis:
  type-aliases-package: com.booksworld # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名

spring:
   application:
    name: admin-provider
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/mydangdang?zeroDateTimeBehavior=convertToNull
    username: root
    password: 123
    dbcp2:
          min-idle: 5 # 数据库连接池的最小维持连接数
          initial-size: 5 # 初始化连接数
          max-total: 5 # 最大连接数
          max-wait-millis: 200 # 等待连接获取的最大超时时间
   jackson:
      date-format: yyyy-MM-dd
      time-zone: GMT+8
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: admin-provider
    prefer-ip-address: true